pipeline {
    agent any

    environment {
        AWS_SHARED_CREDENTIALS_FILE = '/root/.aws/credentials'
        ANSIBLE_GROUP = 'Docker'
        AWS_REGION = 'eu-north-1'
        SSH_PRIVATE_KEY = credentials('ec2-instance-key') // Update with the correct ID
        MASTER_NODE_IP = '13.51.102.35'
        KUBECONFIG_PATH = '/root/project/devops/jenkins-docker/k3s-jenkins.yaml'
        GIT_REPO = 'https://github.com/TiagoLuz9292/solana-spl-momentum-scanner.git'
        GIT_BRANCH = 'master' // Adjust this to your target branch
        INVENTORY_FILE = '/root/project/devops/kubernetes/inventory'
    }

    stages {
        stage('Verify Environment') {
            steps {
                script {
                    // Print environment variables for debugging
                    sh 'printenv | grep AWS'
                    // Print contents of AWS credentials file for debugging
                    sh 'cat $AWS_SHARED_CREDENTIALS_FILE'
                }
            }
        }
        stage('Prepare Environment') {
            steps {
                script {
                    // Ensure the target directory exists and has the right permissions
                    sh 'mkdir -p /root/project/devops/kubernetes'
                    sh 'chmod 755 /root/project/devops/kubernetes'
                    // Print current directory and permissions for debugging
                    sh 'pwd'
                    sh 'ls -ld /root/project/devops/kubernetes'
                }
            }
        }
        stage('Clone Repository') {
            steps {
                // Clone the repository containing the application code and k8s manifests
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
            }
        }
        stage('Add to Known Hosts') {
            steps {
                script {
                    def inventory = readFile("${INVENTORY_FILE}")
                    def hosts = inventory.split('\n').findAll { it.contains('.') }
                    for (host in hosts) {
                        sh "ssh-keyscan -H ${host.split()[0]} >> ~/.ssh/known_hosts"
                    }
                }
            }
        }
        stage('Fetch kubeconfig') {
            steps {
                script {
                    // Fetch the kubeconfig file from the master node
                    sh "scp -i ~/.ssh/my-key-pair ec2-user@$MASTER_NODE_IP:/tmp/k3s-jenkins.yaml $KUBECONFIG_PATH"
                }
            }
        }
        stage('Deploy to K3s') {
            steps {
                script {
                    // Apply Kubernetes manifests for backend and frontend
                    sh 'kubectl apply -f kubernetes/k8s-manifests/backend-deployment.yaml --kubeconfig=$KUBECONFIG_PATH'
                    sh 'kubectl apply -f kubernetes/k8s-manifests/backend-service.yaml --kubeconfig=$KUBECONFIG_PATH'
                    sh 'kubectl apply -f kubernetes/k8s-manifests/frontend-deployment.yaml --kubeconfig=$KUBECONFIG_PATH'
                    sh 'kubectl apply -f kubernetes/k8s-manifests/frontend-service.yaml --kubeconfig=$KUBECONFIG_PATH'
                }
            }
        }
    }
    post {
        cleanup {
            cleanWs()
        }
    }
}